import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Defenser</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-4 ">
        <h1 className="text-4xl font-bold text-black">Defenser</h1>

        <div className="flex flex-col gap-4 ">
          <button className="rounded-md bg-purple-700 p-4 text-lg text-purple-50 transition-all hover:bg-purple-600">
            <Link href={"/dashboard"}>Entrar como administrador</Link>
          </button>
          <button className="rounded-md bg-purple-700 p-4 text-lg text-purple-50 transition-all hover:bg-purple-600">
            <Link href={"/aplicador"}>Entrar como usuário</Link>
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
